spring:
  application:
    name: college-erp
    
  # Swagger/OpenAPI Configuration
  doc:
    api-docs:
      path: /v3/api-docs
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
      doc-expansion: none
      enabled: true
    show-actuator: true

  profiles:
    active: dev   # default, can be overridden with --spring.profiles.active=prod

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.DataSourceInitializationAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/college_erp
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    initialization-mode: always

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    baseline-version: '1'
    baseline-description: 'Base migration'
    schemas: public
    clean-on-validation-error: true
    init-sql: 'CREATE SCHEMA IF NOT EXISTS public;'
    baseline-handle-mixed: true
    out-of-order: true
    jpa:
      defer-datasource-initialization: true

app:
  jwt:
    secret: mySecretKeyForCollegeERPSystemThatShouldBeVerySecureAndLong
    expiration: 86400000  # 24 hours in milliseconds

server:
  port: 8090

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.flywaydb: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc: TRACE
    org.springframework.jdbc.datasource: TRACE
    org.springframework.orm.jpa: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://<PROD_HOST>:5432/college_erp
    username: <PROD_USER>
    password: <PROD_PASS>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8090

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
