spring:
  application:
    name: college-erp

  profiles:
    active: dev   # default, can be overridden with --spring.profiles.active=prod

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.DataSourceInitializationAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/college_erp
    username: postgres
    password: newpassword
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
    initialization-mode: always

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public
        jdbc:
          lob:
            non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration

app:
  jwt:
    secret: mySecretKeyForCollegeERPSystemThatShouldBeVerySecureAndLong
    expiration: 86400000  # 24 hours in milliseconds

server:
  port: 8090

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.datasource: DEBUG
    com.zaxxer.hikari: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://<PROD_HOST>:5432/college_erp
    username: <PROD_USER>
    password: <PROD_PASS>
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        default_schema: public

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8090

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
